FROM microsoft/dotnet:2.1-sdk-bionic AS build
WORKDIR /src
COPY . ./

RUN dotnet restore
RUN dotnet publish -c release -o out


FROM microsoft/dotnet:aspnetcore-runtime

WORKDIR /app
COPY --from=build /src/BookTrader.Web/out/ .
ENV ASPNETCORE_URLS http://*:80
EXPOSE 80
EXPOSE 5000
ENTRYPOINT ["dotnet", "BookTrader.Web.dll"]

# docker build . -t book-trader -f ./Dockerfile.fullBuild
