version: '3'
services:
  postgres:
    image: postgres:10.5
    volumes:
    - devel-trader-db:/var/lib/postgresql
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: book
  pgadmin:
    image: dpage/pgadmin4
    volumes:
    - ../volume/pgadmin:/var/lib/pgadmin
    ports:
    - "20080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
volumes:
  devel-trader-db:
